# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 119b98c7769fac0940ea8377f3ebf475d1a47da9d8d46c0ae265446ff1283c5c0772212f800893499d8501daf88eb90b783c5a2f58168e5ce906c63580bca91d

test:
  secret_key_base: 7404f581672c28188863620b299a628a9a6e301ef2be51ca80b8d6069d7cb11fb8ea0538e479cebb5a1708c886485f7c0018d151177fc316e6de1c802ea3382b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
